/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetorpg;

import ferramentas.CaixaDeDialogo;
import java.util.Random;

/**
 *
 * @author luis.nicolay
 */
public class TelaConfronto extends javax.swing.JFrame {
    
    Personagem personagem;
    Oponente oponente = new Oponente();
    Random gerador = new Random();
    int valorDadoJogar;
    int valorDado;
    int valorDado1;
    Principal principal = new Principal();

    /**
     * Creates new form TelaConfronto
     */
    public TelaConfronto(Personagem personagem) {
        initComponents();
        
        this.personagem = personagem;
        //Preenche os dados do personagem
        /*lblNome.setText(personagem.getNome());
        lblClasse.setText(personagem.getClasse());
        lblNivel.setText(String.valueOf(personagem.getNivel()));
        lblVida.setText(String.valueOf(personagem.getVida()));
        lblAtaque.setText(String.valueOf(personagem.getAtaque()));*/
        mostrarPersonagem();
        mostrarOponente();
        lblValorDado.setText("Sua vez de Atacar, " + personagem.getNome());
        /*lblValorDadoPersonagem.setText(String.valueOf(valorDado));
        lblValorDadoOponente.setText(String.valueOf(valorDado1));*/
    }
    
    private void mostrarPersonagem(){
        lblNome.setText(personagem.getNome());
        lblClasse.setText(personagem.getClasse());
        lblNivel.setText(String.valueOf(personagem.getNivel()));
        lblVida.setText(String.valueOf(personagem.getVida()));
        lblAtaque.setText(String.valueOf(personagem.getAtaque()));
    }
    
    private void gerarOponente() {
        try {
            oponente.setAtaque(gerador.nextInt(35) + 1);
            oponente.setVida(gerador.nextInt(100) + 1);
            oponente.setNivel(gerador.nextInt(10) + 1);
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage().toString(),'e');
        }
    }
    
    private void mostrarOponente(){
        lblNivelOponente.setText(String.valueOf(oponente.getNivel()));
        lblVidaOponente.setText(String.valueOf(oponente.getVida()));
        lblAtaqueOponente.setText(String.valueOf(oponente.getAtaque()));
    }
    
    private void ataquePersonagem(){
        //personagem ataca o oponente
        int ataquePersonagem = 0;
        int valorDado = gerador.nextInt(20) + 1;
        
        lblValorDadoPersonagem.setText(String.valueOf(valorDado));
        
        if(gerador.nextInt(20) + 1 > 13) {//ataque critico
            ataquePersonagem = personagem.getAtaque() / 2;
        }else{
            ataquePersonagem = personagem.getAtaque() / 3;
        }
        System.out.println("Dado: " + valorDado);
        System.out.println("Ataque: " + ataquePersonagem);
        
        //int ataque = personagem.getAtaque();
        int vidaRestante = oponente.getVida() - ataquePersonagem;
        oponente.setVida(vidaRestante);                
    }
        
    private void ataqueOponente(){
        int ataqueOponente = 0;
        int valorDado1 = gerador.nextInt(20) + 1;
        
        lblValorDadoOponente.setText(String.valueOf(valorDado1));
        
        if(gerador.nextInt(20) + 1 > 13) {//ataque critico
            ataqueOponente = personagem.getAtaque() / 2;
        }else{
            ataqueOponente = personagem.getAtaque() / 3;
        }
        System.out.println("Dado: " + valorDado1);
        System.out.println("Ataque: " + ataqueOponente);
        
        //int ataque = personagem.getAtaque();
        int vidaRestante = personagem.getVida() - ataqueOponente;
        personagem.setVida(vidaRestante);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblClasse = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblVida = new javax.swing.JLabel();
        lblAtaque = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblVidaOponente = new javax.swing.JLabel();
        lblAtaqueOponente = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblNivelOponente = new javax.swing.JLabel();
        btnAtacar = new javax.swing.JButton();
        lblValorDado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblValorDadoOponente = new javax.swing.JLabel();
        lblValorDadoPersonagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nome:");

        jLabel5.setText("Vida:");

        jLabel3.setText("Classe:");

        jLabel4.setText("Nível:");

        jLabel1.setText("Ataque:");

        lblNome.setText("...");

        lblClasse.setText("...");

        lblNivel.setText("...");

        lblVida.setText("...");

        lblAtaque.setText("...");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setText("X");

        lblVidaOponente.setText("...");

        lblAtaqueOponente.setText("...");

        jLabel8.setText("Vida:");

        jLabel10.setText("Nível:");

        jLabel11.setText("Ataque:");

        lblNivelOponente.setText("...");

        btnAtacar.setText("Atacar");
        btnAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtacarActionPerformed(evt);
            }
        });

        lblValorDado.setText("...");

        jLabel7.setText("Valor do Dado Jogado: ");

        jLabel9.setText("Valor do Dado Jogado: ");

        lblValorDadoOponente.setText("...");

        lblValorDadoPersonagem.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtacar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblVida))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAtaque))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNivel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNome)))
                                .addGap(315, 315, 315))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblClasse)
                                .addGap(319, 319, 319))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorDadoPersonagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVidaOponente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAtaqueOponente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNivelOponente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorDadoOponente)))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(lblValorDado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(lblNivelOponente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(lblVidaOponente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(lblAtaqueOponente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(lblValorDadoOponente))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(lblValorDado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtacar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblClasse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblNivel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblVida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAtaque)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblValorDadoPersonagem))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacarActionPerformed
        // TODO add your handling code here:
        valorDadoJogar = gerador.nextInt(2) + 1;
        //lblValorDado.setText(String.valueOf(valorDadoJogar));
        
        if(valorDadoJogar == 1){
            lblValorDado.setText("Sua vez de Atacar, " + personagem.getNome());
        }else{
            lblValorDado.setText("Você está sendo atacado!!!");
        }
        
        if(valorDadoJogar == 1){
            ataquePersonagem();
            mostrarOponente();
        }else{
            ataqueOponente();
            mostrarPersonagem();
        }
        
        ataquePersonagem();
        
        if(oponente.getVida() > 0){
            mostrarOponente();
        }else{
            gerarOponente();
            mostrarOponente();
        }
        
        ataqueOponente();     
              
        if(personagem.getVida() <= 0){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Sua vida acabou!!" + "\nSE FODEU","ERRRRROOOOOU",'e');
               //System.exit(0);
               this.dispose();
               principal.setVisible(true);           
        }        
    }//GEN-LAST:event_btnAtacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfronto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfronto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfronto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfronto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfronto(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtacar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAtaque;
    private javax.swing.JLabel lblAtaqueOponente;
    private javax.swing.JLabel lblClasse;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNivelOponente;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblValorDado;
    private javax.swing.JLabel lblValorDadoOponente;
    private javax.swing.JLabel lblValorDadoPersonagem;
    private javax.swing.JLabel lblVida;
    private javax.swing.JLabel lblVidaOponente;
    // End of variables declaration//GEN-END:variables
}
